name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Autentikasi dengan npm
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .>
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependensi
        run: npm install

      - name: Publish ke npm
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
